"""
Data models and schemas for SIF Sentinel Phase 5E Narrative Translation & Explainability Layer.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import StrEnum
from typing import Any

from pydantic import BaseModel, Field


class NarrativeMode(StrEnum):
    EXECUTIVE = "EXECUTIVE"
    INVESTIGATION = "INVESTIGATION"
    FIELD = "FIELD"
    COUNTERFACTUAL = "COUNTERFACTUAL"


class SourceBasis(StrEnum):
    CAUSAL_GRAPH = "CAUSAL_GRAPH"
    RISK_ENGINE = "RISK_ENGINE"
    COUNTERFACTUAL = "COUNTERFACTUAL"
    EVIDENCE = "EVIDENCE"
    LSR_MAPPING = "LSR_MAPPING"


class ValidationStatus(StrEnum):
    VALID = "VALID"
    FALLBACK_APPLIED = "FALLBACK_APPLIED"
    REJECTED = "REJECTED"


class ActionPriority(StrEnum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


@dataclass
class BarrierAnalysisItem:
    control: str
    observed_status: str
    failure: bool
    explanation: str
    source_basis: SourceBasis = SourceBasis.CAUSAL_GRAPH

    def to_dict(self) -> dict[str, Any]:
        return {
            "control": self.control,
            "observed_status": self.observed_status,
            "failure": self.failure,
            "explanation": self.explanation,
            "source_basis": self.source_basis.value,
        }


@dataclass
class RecommendedActionItem:
    action: str
    reason: str
    priority: ActionPriority
    source_basis: SourceBasis
    target_control: str | None = None

    def to_dict(self) -> dict[str, Any]:
        return {
            "action": self.action,
            "reason": self.reason,
            "priority": self.priority.value,
            "source_basis": self.source_basis.value,
            "target_control": self.target_control,
        }


@dataclass
class GroundingItem:
    claim: str
    source_type: SourceBasis
    source_reference: str

    def to_dict(self) -> dict[str, Any]:
        return {
            "claim": self.claim,
            "source_type": self.source_type.value,
            "source_reference": self.source_reference,
        }


@dataclass
class ValidationResult:
    is_valid: bool
    status: ValidationStatus
    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "is_valid": self.is_valid,
            "status": self.status.value,
            "errors": self.errors,
            "warnings": self.warnings,
        }


@dataclass
class NarrativeContext:
    """
    Read-only structured safety context assembled from deterministic engines.
    Acts as the authoritative single source of truth for narrative generation.
    """
    incident_text: str
    sif_potential: bool
    sif_level: str
    model_probability: float
    risk_score: int
    risk_priority: str
    activity: str | None
    hazard: str | None
    is_high_energy_hazard: bool
    barrier: str | None
    barrier_status: str
    barrier_failure: bool
    life_saving_rule: str | None
    evidence_span: str | None
    evidence_terms: list[str]
    causal_chains: list[dict[str, Any]]
    confidence: float
    reasoning_summary: str | None
    counterfactual: dict[str, Any] | None = None
    prevention_detected: bool = False
    temporal_inversion: bool = False
    created_at: str = field(default_factory=lambda: datetime.now(UTC).isoformat())

    def to_dict(self) -> dict[str, Any]:
        return {
            "incident_text": self.incident_text,
            "sif_potential": self.sif_potential,
            "sif_level": self.sif_level,
            "model_probability": round(self.model_probability, 4),
            "risk_score": self.risk_score,
            "risk_priority": self.risk_priority,
            "activity": self.activity,
            "hazard": self.hazard,
            "is_high_energy_hazard": self.is_high_energy_hazard,
            "barrier": self.barrier,
            "barrier_status": self.barrier_status,
            "barrier_failure": self.barrier_failure,
            "life_saving_rule": self.life_saving_rule,
            "evidence_span": self.evidence_span,
            "evidence_terms": self.evidence_terms,
            "causal_chains": self.causal_chains,
            "confidence": round(self.confidence, 4),
            "reasoning_summary": self.reasoning_summary,
            "counterfactual": self.counterfactual,
            "prevention_detected": self.prevention_detected,
            "temporal_inversion": self.temporal_inversion,
            "created_at": self.created_at,
        }


@dataclass
class NarrativeOutput:
    """
    Structured narrative explanation generated by a provider and verified by the validator.
    """
    mode: NarrativeMode
    executive_summary: str
    incident_interpretation: str
    causal_explanation: str
    barrier_analysis: list[BarrierAnalysisItem]
    sif_explanation: str
    risk_explanation: str
    lsr_explanation: str | None
    key_findings: list[str]
    recommended_actions: list[RecommendedActionItem]
    counterfactual_explanation: str | None
    confidence_statement: str
    limitations: list[str]
    grounding: list[GroundingItem]
    validation_status: ValidationStatus = ValidationStatus.VALID
    validation_errors: list[str] = field(default_factory=list)
    provider_name: str = "deterministic"
    model_name: str = "rules_engine"
    latency_ms: float = 0.0
    generated_at: str = field(default_factory=lambda: datetime.now(UTC).isoformat())

    def to_dict(self) -> dict[str, Any]:
        return {
            "mode": self.mode.value,
            "executive_summary": self.executive_summary,
            "incident_interpretation": self.incident_interpretation,
            "causal_explanation": self.causal_explanation,
            "barrier_analysis": [b.to_dict() for b in self.barrier_analysis],
            "sif_explanation": self.sif_explanation,
            "risk_explanation": self.risk_explanation,
            "lsr_explanation": self.lsr_explanation,
            "key_findings": self.key_findings,
            "recommended_actions": [r.to_dict() for r in self.recommended_actions],
            "counterfactual_explanation": self.counterfactual_explanation,
            "confidence_statement": self.confidence_statement,
            "limitations": self.limitations,
            "grounding": [g.to_dict() for g in self.grounding],
            "validation_status": self.validation_status.value,
            "validation_errors": self.validation_errors,
            "provider_name": self.provider_name,
            "model_name": self.model_name,
            "latency_ms": round(self.latency_ms, 3),
            "generated_at": self.generated_at,
        }


# ==========================================
# Pydantic Schemas for API Layer
# ==========================================

class NarrativeBarrierAnalysisSchema(BaseModel):
    control: str
    observed_status: str
    failure: bool
    explanation: str
    source_basis: str = "CAUSAL_GRAPH"


class NarrativeActionSchema(BaseModel):
    action: str
    reason: str
    priority: str
    source_basis: str
    target_control: str | None = None


class NarrativeGroundingSchema(BaseModel):
    claim: str
    source_type: str
    source_reference: str


class NarrativeRequest(BaseModel):
    incident_text: str = Field(min_length=1, max_length=20_000)
    mode: NarrativeMode = NarrativeMode.EXECUTIVE
    safety_graph: dict[str, Any] | None = None
    causal_chains: list[dict[str, Any]] | None = None
    risk_score: int | None = None
    risk_priority: str | None = None
    sif_potential: bool | None = None
    sif_level: str | None = None
    life_saving_rule: str | None = None
    evidence_span: str | None = None
    evidence_terms: list[str] = Field(default_factory=list)
    counterfactual_scenario: dict[str, Any] | None = None
    confidence: float | None = None


class NarrativeResponse(BaseModel):
    mode: str
    executive_summary: str
    incident_interpretation: str
    causal_explanation: str
    barrier_analysis: list[NarrativeBarrierAnalysisSchema]
    sif_explanation: str
    risk_explanation: str
    lsr_explanation: str | None = None
    key_findings: list[str]
    recommended_actions: list[NarrativeActionSchema]
    counterfactual_explanation: str | None = None
    confidence_statement: str
    limitations: list[str]
    grounding: list[NarrativeGroundingSchema]
    validation_status: str
    validation_errors: list[str] = Field(default_factory=list)
    provider_name: str
    model_name: str
    latency_ms: float
    generated_at: str
