import { ArrowRight, CheckCircle2, ShieldCheck, UsersRound } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { Header, PageContainer, SectionContainer } from "@/components/layout";

const principles = [
  { icon: ShieldCheck, title: "Structured safety signals", text: "A clear home for consistent incident and near-miss information." },
  { icon: CheckCircle2, title: "Deterministic by design", text: "Evidence-led analysis is kept distinct from optional reviewer assistance." },
  { icon: UsersRound, title: "Human decision authority", text: "Review remains visible, accountable, and central to every safety decision." },
];

export default function Home() {
  return <div className="min-h-screen bg-background"><Header /><main><SectionContainer className="overflow-hidden"><PageContainer><div className="grid items-center gap-10 lg:grid-cols-[1.15fr_.85fr] lg:gap-16"><div><Badge variant="secondary">Safety intelligence foundation</Badge><h1 className="mt-6 max-w-3xl text-4xl font-semibold tracking-tight text-balance sm:text-5xl lg:text-6xl">Make safety signals easier to see, understand, and review.</h1><p className="mt-6 max-w-2xl text-base leading-7 text-muted-foreground sm:text-lg">SIF Sentinel brings disciplined structure to operational safety information—supporting meaningful review without replacing professional judgment.</p><div className="mt-8 flex items-center gap-2 text-sm font-medium text-primary"><span>Foundation release</span><ArrowRight className="size-4" aria-hidden="true" /></div></div><Card className="border-primary/15 bg-card"><CardHeader><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-lg bg-primary text-primary-foreground"><ShieldCheck className="size-5" aria-hidden="true" /></span><div><CardTitle>Designed for careful work</CardTitle><CardDescription>Purposeful tools, ready to grow.</CardDescription></div></div></CardHeader><CardContent><div className="space-y-4 text-sm leading-6 text-muted-foreground"><p>The workspace foundation is ready for authenticated, role-aware safety operations in the next phase.</p><Separator /><p>Until then, no operational status, incident data, or risk scoring is represented here.</p></div></CardContent></Card></div></PageContainer></SectionContainer><SectionContainer className="border-t border-border bg-muted/30"><PageContainer><div className="max-w-2xl"><p className="text-sm font-semibold text-primary">Our operating principles</p><h2 className="mt-3 text-2xl font-semibold tracking-tight sm:text-3xl">Clarity before complexity.</h2></div><div className="mt-8 grid gap-4 md:grid-cols-3">{principles.map(({ icon: Icon, title, text }) => <Card key={title} className="h-full"><CardHeader><Icon className="size-5 text-primary" aria-hidden="true" /><CardTitle className="mt-4">{title}</CardTitle><CardDescription className="leading-6">{text}</CardDescription></CardHeader></Card>)}</div></PageContainer></SectionContainer></main><footer className="border-t border-border"><PageContainer className="flex min-h-16 items-center text-sm text-muted-foreground">SIF Sentinel · Safety intelligence with human oversight</PageContainer></footer></div>;
}
