"""Add Phase J LLM metadata to report_analyses

Revision ID: f36b3761116e
Revises: 202609020003
Create Date: 2026-09-03 11:54:10.864977
"""
from alembic import op
import sqlalchemy as sa

revision = 'f36b3761116e'
down_revision = '202609020003'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('precursor_candidates',
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('activity', sa.String(length=255), nullable=True),
    sa.Column('hazard', sa.String(length=255), nullable=True),
    sa.Column('barrier', sa.String(length=255), nullable=True),
    sa.Column('failure_type', sa.String(length=255), nullable=True),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_precursor_candidates_category'), 'precursor_candidates', ['category'], unique=False)
    op.create_index(op.f('ix_precursor_candidates_report_id'), 'precursor_candidates', ['report_id'], unique=False)
    op.add_column('precursor_patterns', sa.Column('category', sa.String(length=255), server_default='Unknown', nullable=False))
    op.add_column('precursor_patterns', sa.Column('priority', sa.String(length=50), server_default='LOW', nullable=False))
    op.drop_index(op.f('ix_precursor_patterns_risk_level'), table_name='precursor_patterns')
    op.create_index(op.f('ix_precursor_patterns_category'), 'precursor_patterns', ['category'], unique=False)
    op.create_index('ix_precursor_patterns_priority', 'precursor_patterns', ['priority'], unique=False)
    op.drop_column('precursor_patterns', 'risk_level')
    op.add_column('report_analyses', sa.Column('model_probability', sa.Float(), nullable=True))
    op.add_column('report_analyses', sa.Column('risk_score', sa.Float(), nullable=True))
    op.add_column('report_analyses', sa.Column('risk_priority', sa.String(length=50), nullable=True))
    op.add_column('report_analyses', sa.Column('risk_components', sa.JSON(), nullable=True))
    op.add_column('report_analyses', sa.Column('risk_version', sa.String(length=50), nullable=True))
    op.add_column('report_analyses', sa.Column('llm_attempted', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('report_analyses', sa.Column('llm_used', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('report_analyses', sa.Column('llm_provider', sa.String(length=50), nullable=True))
    op.add_column('report_analyses', sa.Column('llm_model_used', sa.String(length=100), nullable=True))
    op.add_column('report_analyses', sa.Column('llm_timestamp', sa.DateTime(), nullable=True))
    op.add_column('report_analyses', sa.Column('reviewer_summary', sa.Text(), nullable=True))
    op.add_column('report_analyses', sa.Column('llm_error_code', sa.String(length=100), nullable=True))
    op.drop_column('report_analyses', 'sif_probability')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_analyses', sa.Column('sif_probability', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('report_analyses', 'llm_error_code')
    op.drop_column('report_analyses', 'reviewer_summary')
    op.drop_column('report_analyses', 'llm_timestamp')
    op.drop_column('report_analyses', 'llm_model_used')
    op.drop_column('report_analyses', 'llm_provider')
    op.drop_column('report_analyses', 'llm_used')
    op.drop_column('report_analyses', 'llm_attempted')
    op.drop_column('report_analyses', 'risk_version')
    op.drop_column('report_analyses', 'risk_components')
    op.drop_column('report_analyses', 'risk_priority')
    op.drop_column('report_analyses', 'risk_score')
    op.drop_column('report_analyses', 'model_probability')
    op.add_column('precursor_patterns', sa.Column('risk_level', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_index('ix_precursor_patterns_priority', table_name='precursor_patterns')
    op.drop_index(op.f('ix_precursor_patterns_category'), table_name='precursor_patterns')
    op.create_index(op.f('ix_precursor_patterns_risk_level'), 'precursor_patterns', ['risk_level'], unique=False)
    op.drop_column('precursor_patterns', 'priority')
    op.drop_column('precursor_patterns', 'category')
    op.drop_index(op.f('ix_precursor_candidates_report_id'), table_name='precursor_candidates')
    op.drop_index(op.f('ix_precursor_candidates_category'), table_name='precursor_candidates')
    op.drop_table('precursor_candidates')
    # ### end Alembic commands ###
