"""Add Phase J LLM metadata to report_analyses

Revision ID: f36b3761116e
Revises: 202609020003
Create Date: 2026-09-03 11:54:10.864977
"""
import sqlalchemy as sa

from alembic import op

revision = 'f36b3761116e'
down_revision = '202609020003'
branch_labels = None
depends_on = None

def upgrade():
    """Apply Phase I/J fields to older databases without reapplying current metadata."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = set(inspector.get_table_names())
    if "precursor_candidates" not in tables:
        op.create_table(
            "precursor_candidates",
            sa.Column("report_id", sa.Uuid(), sa.ForeignKey("reports.id"), nullable=False),
            sa.Column("category", sa.String(length=255), nullable=False),
            sa.Column("activity", sa.String(length=255)),
            sa.Column("hazard", sa.String(length=255)),
            sa.Column("barrier", sa.String(length=255)),
            sa.Column("failure_type", sa.String(length=255)),
            sa.Column("evidence_text", sa.Text()),
            sa.Column("id", sa.Uuid(), primary_key=True, nullable=False),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        )
        op.create_index("ix_precursor_candidates_category", "precursor_candidates", ["category"])
        op.create_index("ix_precursor_candidates_report_id", "precursor_candidates", ["report_id"])

    pattern_columns = {column["name"] for column in inspector.get_columns("precursor_patterns")}
    pattern_indexes = {index["name"] for index in inspector.get_indexes("precursor_patterns")}
    if "category" not in pattern_columns:
        op.add_column("precursor_patterns", sa.Column("category", sa.String(length=255), server_default="UNKNOWN", nullable=False))
    if "priority" not in pattern_columns:
        op.add_column("precursor_patterns", sa.Column("priority", sa.String(length=50), server_default="LOW", nullable=False))
    if "ix_precursor_patterns_risk_level" in pattern_indexes:
        op.drop_index("ix_precursor_patterns_risk_level", table_name="precursor_patterns")
    if "ix_precursor_patterns_category" not in pattern_indexes:
        op.create_index("ix_precursor_patterns_category", "precursor_patterns", ["category"])
    if "ix_precursor_patterns_priority" not in pattern_indexes:
        op.create_index("ix_precursor_patterns_priority", "precursor_patterns", ["priority"])
    if "risk_level" in pattern_columns:
        op.drop_column("precursor_patterns", "risk_level")

    analysis_columns = {column["name"] for column in inspector.get_columns("report_analyses")}
    additions = (
        ("model_probability", sa.Float()), ("risk_score", sa.Float()),
        ("risk_priority", sa.String(length=50)), ("risk_components", sa.JSON()),
        ("risk_version", sa.String(length=50)),
        ("llm_attempted", sa.Boolean(), "0", False), ("llm_used", sa.Boolean(), "0", False),
        ("llm_provider", sa.String(length=50)), ("llm_model_used", sa.String(length=100)),
        ("llm_timestamp", sa.DateTime(timezone=True)), ("reviewer_summary", sa.Text()),
        ("llm_error_code", sa.String(length=100)),
    )
    for addition in additions:
        name, column_type, *default = addition
        if name not in analysis_columns:
            kwargs = {"nullable": default[1]} if default else {"nullable": True}
            if default:
                kwargs["server_default"] = default[0]
            op.add_column("report_analyses", sa.Column(name, column_type, **kwargs))
    if "sif_probability" in analysis_columns:
        op.drop_column("report_analyses", "sif_probability")

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_analyses', sa.Column('sif_probability', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('report_analyses', 'llm_error_code')
    op.drop_column('report_analyses', 'reviewer_summary')
    op.drop_column('report_analyses', 'llm_timestamp')
    op.drop_column('report_analyses', 'llm_model_used')
    op.drop_column('report_analyses', 'llm_provider')
    op.drop_column('report_analyses', 'llm_used')
    op.drop_column('report_analyses', 'llm_attempted')
    op.drop_column('report_analyses', 'risk_version')
    op.drop_column('report_analyses', 'risk_components')
    op.drop_column('report_analyses', 'risk_priority')
    op.drop_column('report_analyses', 'risk_score')
    op.drop_column('report_analyses', 'model_probability')
    op.add_column('precursor_patterns', sa.Column('risk_level', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_index('ix_precursor_patterns_priority', table_name='precursor_patterns')
    op.drop_index(op.f('ix_precursor_patterns_category'), table_name='precursor_patterns')
    op.create_index(op.f('ix_precursor_patterns_risk_level'), 'precursor_patterns', ['risk_level'], unique=False)
    op.drop_column('precursor_patterns', 'priority')
    op.drop_column('precursor_patterns', 'category')
    op.drop_index(op.f('ix_precursor_candidates_report_id'), table_name='precursor_candidates')
    op.drop_index(op.f('ix_precursor_candidates_category'), table_name='precursor_candidates')
    op.drop_table('precursor_candidates')
    # ### end Alembic commands ###
